name: Validate

on:
  push:
    branches: [main]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build website
        run: npm run build:website

      - name: Build client
        run: npm run build:client

      - name: Build server
        run: npm run build:server

      - name: Lint website
        run: npm run lint:website

      - name: Lint server
        run: npm run lint:server
